### ISSUE TITLE
Name of repeating group

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-json-encoding-spec#3]
The spec currently says

> The name of a repeating group is the name of the associated NumInGroup field name as it appears in the FIX repository.

Why not use the name of the repeating group from the repository rather than its associated NumInGrp counter? Especially since JSON encoding doesn't need the array counter.

The example gives NoMDEntries as the repeating group object name. The repository gives two repeating group components that use that same counter, MDFullGrp and MDIncGrp. It should be one of those names to distinguish which group.

**Comment by salsferrazza** [comment]
I agree with this suggestion. 

Overall, this approach would yield richer semantics within the encoded messages themselves.

So presumably the output would resemble (within the `body` of the JSON):

```
...
  "ApplVerID": "9",
  "BodyLength": "278",
  "MsgType": "X",
  "SenderCompID": "CME",
  "TradeDate": "20160315",
  "MsgSeqNum": "3254145",
  "SendingTime": "20160314214500015068553",
  "TransactTime": "20160314214500001107404",
  "MatchEventIndicator": "00001000",
  "MDIncGrp": [
    {
      "MDUpdateAction": "0",
      "MDEntryType": "4",
      "SecurityID": "827723",
      "Symbol": "ZSK6",
      "RptSeq": "717363",
      "MDEntryPx": "894.25",
      "OpenCloseSettlFlag": "5"
    },
    {
      "MDUpdateAction": "0",
      "MDEntryType": "4",
      "SecurityID": "401316",
      "Symbol": "ZSN6",
      "RptSeq": "621346",
      "MDEntryPx": "898.0",
      "OpenCloseSettlFlag": "5"
    },
    {
      "MDUpdateAction": "0",
      "MDEntryType": "4",
      "SecurityID": "253214",
      "Symbol": "ZSX6",
      "RptSeq": "617653",
      "MDEntryPx": "904.5",
      "OpenCloseSettlFlag": "5"
    }
  ],
...
```

**Comment by mgatny** [comment]
For some background -- we reached consensus on using the NumInGrp counter on the Aug 15, 2016 conference call because:
1. The NumInGroup name is manifest from the tag=value FIX representation.  I.e. you can go back and forth between plain FIX and JSON without a Repository lookup if you cannot or do not want to do one.
2. Components did not exist in FIX.4.2 (still widely used) and earlier.

Can we satisfy 1 and 2 above using Component name only? Let's discuss on the next conference call.
